// Copies the conformance fixtures from `packages/schema/fixtures` into this package.
//
//   dart tool/sync_fixtures.dart            (run from sdks/flutter; uses dart:io only)
//
// Outputs:
//   assets/default_theme.json               bundled last-resort fallback (asset)
//   lib/src/generated/default_theme.g.dart  same JSON as a Dart constant (sync access)
//   test/fixtures/*.json                    fixtures used by the test suite
//   example/assets/themes/*.json            themes for the example's offline demo mode
import 'dart:convert';
import 'dart:io';

void main() {
  final pkg = Directory.current;
  final source = Directory('${pkg.path}/../../packages/schema/fixtures');
  if (!source.existsSync()) {
    stderr.writeln('Fixtures not found at ${source.path}. Run from sdks/flutter.');
    exit(1);
  }

  final targets = ['test/fixtures', 'example/assets/themes'];
  final fixtures = source.listSync().whereType<File>().where((f) => f.path.endsWith('.json'));
  for (final target in targets) {
    final dir = Directory('${pkg.path}/$target')..createSync(recursive: true);
    for (final file in fixtures) {
      final name = file.uri.pathSegments.last;
      file.copySync('${dir.path}/$name');
      stdout.writeln('$target/$name');
    }
  }

  final defaultJson = File('${source.path}/default.json').readAsStringSync();
  Directory('${pkg.path}/assets').createSync(recursive: true);
  File('${pkg.path}/assets/default_theme.json').writeAsStringSync(defaultJson);
  stdout.writeln('assets/default_theme.json');

  // Re-encode compactly; a raw string keeps the generated file readable and escape-free.
  final compact = jsonEncode(jsonDecode(defaultJson));
  Directory('${pkg.path}/lib/src/generated').createSync(recursive: true);
  File('${pkg.path}/lib/src/generated/default_theme.g.dart').writeAsStringSync(
    '// GENERATED by tool/sync_fixtures.dart from packages/schema/fixtures/default.json.\n'
    '// Do not edit by hand.\n\n'
    "const String kDefaultThemeJson = r'''$compact''';\n",
  );
  stdout.writeln('lib/src/generated/default_theme.g.dart');
}
